/* Generated by cbindgen - do not edit manually. */

#ifndef WINPANE_H
#define WINPANE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the last error message, or NULL if no error.
 * The returned pointer is valid until the next winpane call on the same thread.
 */
const char *winpane_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WINPANE_H */
